Imports Microsoft.VisualBasic
Imports System
Imports System.Windows
Imports System.Windows.Controls
Imports System.Windows.Media
Imports DevExpress.AgDataGrid
Imports DevExpress.Xpf.Editors

Namespace AgDataGrid_ConditionalFormatting
	Partial Public Class MainPage
		Inherits UserControl
		Public Sub New()
			InitializeComponent()
			grid.DataSource = ProductList.GetData()
		End Sub

		Private Sub grid_ColumnsAutoGenerated(ByVal sender As Object, ByVal e As EventArgs)
			AddHandler grid.Columns("UnitPrice").PrepareCellDisplayElement, AddressOf unitPriceColumn_PrepareCellDisplayElement
		End Sub

		Private Sub unitPriceColumn_PrepareCellDisplayElement(ByVal sender As Object, ByVal e As PrepareCellDisplayElementEventArgs)
				If CDbl(e.CellData) > 20 Then
					CType(e.DisplayElement, TextEdit).Foreground = New SolidColorBrush(Colors.Red)
					CType(e.DisplayElement, TextEdit).Background = New SolidColorBrush(Colors.Yellow)
					CType(e.DisplayElement, TextEdit).FontWeight = FontWeights.Bold
				End If
		End Sub
	End Class
End Namespace
