using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using DevExpress.AgDataGrid;
using DevExpress.AgEditors;

namespace AgDataGrid_ConditionalFormatting {
    public partial class MainPage : UserControl {
        public MainPage() {
            InitializeComponent();
            grid.DataSource = ProductList.GetData();
        }

        private void grid_ColumnsAutoGenerated(object sender, EventArgs e) {
            grid.Columns["UnitPrice"].PrepareCellDisplayElement +=
                new PrepareCellDisplayElementEventHandler(unitPriceColumn_PrepareCellDisplayElement);
        }

        private void unitPriceColumn_PrepareCellDisplayElement(object sender,
            PrepareCellDisplayElementEventArgs e) {
            if (e.CellData != null && ((Product)e.CellData.RowValue).UnitPrice > 20) {
                ((TextEdit)e.DisplayElement).Foreground = new SolidColorBrush(Colors.Red);
                ((TextEdit)e.DisplayElement).Background = new SolidColorBrush(Colors.Yellow);
                ((TextEdit)e.DisplayElement).FontWeight = FontWeights.Bold;
            }
        }
    }
}
